version: '3.8'  # Указывает версию Docker Compose файла.

services:  # Определяет набор контейнеров (сервисов), которые должны быть запущены в рамках вашего приложения.

  backend:  # Имя сервиса (контейнера) для вашего backend приложения.
    build: .  # Указывает Docker на необходимость сборки образа из Dockerfile, который находится в текущей директории.
    ports:
      - "8999:8080"  # Проброс порта: делает приложение доступным на порту 8999 хоста, перенаправляя его на порт 8080 внутри контейнера.
    environment:  # Определение переменных окружения, которые будут доступны внутри контейнера.
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/smart_test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true  # JDBC URL для подключения к базе данных MySQL.
      SPRING_DATASOURCE_USERNAME: root  # Имя пользователя для подключения к базе данных.
      SPRING_DATASOURCE_PASSWORD: root  # Пароль пользователя для подключения к базе данных.
    depends_on:  # Задает зависимости сервиса. Указывает, что сервис backend должен быть запущен после запуска сервиса db.
      - db

  db:  # Имя сервиса (контейнера) для базы данных MySQL.
    image: mysql:8.0  # Имя образа Docker для базы данных MySQL версии 8.0, который будет использоваться для создания контейнера.
    environment:  # Определение переменных окружения для контейнера MySQL.
      MYSQL_DATABASE: smart_test  # Имя базы данных, которая будет создана автоматически при запуске контейнера.
      MYSQL_ROOT_PASSWORD: root  # Пароль для пользователя root базы данных.
    ports:
      - "8881:3306"  # Проброс порта: делает базу данных доступной на порту 8881 хоста, перенаправляя его на порт 3306 внутри контейнера.
    volumes:  # Тома используются для сохранения данных базы данных вне контейнера, чтобы они не терялись при перезапуске контейнера.
      - mysql_data:/var/lib/mysql  # Определяет том для хранения данных MySQL.

volumes:  # Определение томов, используемых в этом файле docker-compose.
  mysql_data:  # Имя тома для данных MySQL.
